<!doctype html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Kode Akses Hasil Analisis</title>
  </head>
  <body style="margin:0;padding:0;background:#eef2ff;font-family:Arial,sans-serif;color:#1f2a44;">
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#eef2ff;padding:24px 12px;">
      <tr>
        <td align="center">
          <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:680px;background:#ffffff;border:1px solid #dbe5ff;border-radius:12px;overflow:hidden;">
            <tr>
              <td style="padding:28px 28px 12px 28px;text-align:center;">
                <p style="margin:10px 0 4px 0;font-size:36px;line-height:1;font-weight:700;color:#2E3F86;">AI Review Fastrack</p>
                <p style="margin:0;font-size:14px;color:#5d6b91;">Developed by Fastrack</p>
              </td>
            </tr>

            <tr>
              <td style="padding:22px 28px 0 28px;text-align:center;">
                <p style="margin:0;font-size:22px;font-weight:700;letter-spacing:0.08em;color:#5E74C9;">REVIEW COMPLETE</p>
                <h1 style="margin:22px 0 0 0;font-size:42px;line-height:1.2;color:#0f172a;">Your Paper Review is Ready!</h1>
              </td>
            </tr>

            <tr>
              <td style="padding:28px;">
                <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border:2px solid #c7d6ff;border-radius:12px;background:#ffffff;">
                  <tr>
                    <td style="padding:18px 20px;">
                      <p style="margin:0 0 10px 0;font-size:18px;font-weight:700;letter-spacing:0.06em;color:#2E3F86;">PAPER TITLE</p>
                      <p style="margin:0;font-size:29px;line-height:1.4;font-weight:700;color:#111827;">
                        {{ $analysis->doc_name }}
                      </p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:8px 28px 0 28px;text-align:center;">
                <p style="margin:0;font-size:34px;font-weight:700;color:#9ca3af;">View Your Review</p>
              </td>
            </tr>

            <tr>
              <td style="padding:20px 28px 0 28px;">
                <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border-left:4px solid #5E74C9;background:#ffffff;border-radius:8px;">
                  <tr>
                    <td style="padding:16px 16px 8px 16px;font-size:20px;line-height:1.5;color:#1f2937;">
                      <strong>Alternative access:</strong>
                      @if($resultUrl)
                        Visit <a href="{{ $resultUrl }}" style="color:#5E74C9;font-weight:700;text-decoration:none;">{{ $resultUrl }}</a> and enter your token manually.
                      @else
                        Enter your token manually on halaman buka hasil.
                      @endif
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:0 16px 16px 16px;">
                      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f9fafb;border:1px solid #d1d5db;border-radius:6px;">
                        <tr>
                          <td style="padding:12px 14px;">
                            <p style="margin:0 0 8px 0;font-size:13px;color:#374151;">Your Access Token:</p>
                            <p style="margin:0;font-family:'Courier New',monospace;font-size:18px;font-weight:700;color:#2E3F86;letter-spacing:0.02em;word-break:break-word;">
                              {{ $accessCode }}
                            </p>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:24px 28px 0 28px;">
                <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f5f8ff;border:1px solid #c7d6ff;border-radius:10px;">
                  <tr>
                    <td style="padding:14px 16px;text-align:center;font-size:14px;line-height:1.7;color:#4f629e;">
                      <strong>Important:</strong> This review was generated by an AI system. Please use it as guidance and verify the content. Always apply your own judgment and expertise.
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:24px 28px 28px 28px;text-align:center;">
                <p style="margin:8px 0 0 0;font-size:12px;color:#9ca3af;">&copy; {{ now()->year }} AI Review Fastrack</p>
                @if($resultUrl)
                  <p style="margin:10px 0 0 0;font-size:12px;color:#9ca3af;line-height:1.6;">
                    Halaman buka hasil: <a href="{{ $resultUrl }}" style="color:#6b7280;text-decoration:underline;">{{ $resultUrl }}</a>
                  </p>
                @endif
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
